const express = require('express')
const dotenv = require('dotenv')
const mongoose = require('mongoose')
const morgon = require('morgan')
const app = express()
dotenv.config()
mongoose.connect(process.env.MONGOURL)
app.set('view engine', 'ejs')
app.use(morgon('combined'))
app.use('/', require('./route/index.js'))
app.use('/v1/jobs', require('./api/jobs.js'))
app.listen(process.env.PORT)
console.log(`app is listening at ${process.env.PORT}`)
module.exports = app
